<#
.SYNOPSIS
    Extracts a curated subset of icon entries from latte-soft/lucide-roblox's
    bundled release file and emits src/Core/IconMap.lua (plain data module).

    Source: https://github.com/latte-soft/lucide-roblox (MIT)
    Icons : https://lucide.dev (ISC)

    Re-run whenever you want to add icons: append names to $Wanted and run.
#>

$ErrorActionPreference = "Stop"
$Source = "$env:TEMP\opencode\lucide-roblox.luau"
if (-not (Test-Path $Source)) {
    Invoke-WebRequest -Uri "https://github.com/latte-soft/lucide-roblox/releases/latest/download/lucide-roblox.luau" -OutFile $Source
}
$raw = [System.IO.File]::ReadAllText((Resolve-Path $Source))

# Curated icon set (Lucide 0.363 names). Missing names are reported, not fatal.
$Wanted = @(
	"activity","alarm-clock","alert-circle","alert-octagon","alert-triangle","anchor","antenna","aperture",
	"archive","arrow-down","arrow-left","arrow-right","arrow-up","arrow-up-right","asterisk","at-sign","atom","award","axe",
	"badge-check","ban","battery","battery-charging","bell","bell-off","bluetooth","bold","bomb","book","bookmark","box",
	"briefcase","brush","bug","building",
	"calculator","calendar","camera","cast","check","check-circle","check-square","chevron-down","chevron-left",
	"chevron-right","chevron-up","chevrons-up-down","circle","clipboard","clock","cloud","cloud-download","cloud-upload",
	"code","codepen","codesandbox","coffee","cog","coins","command","compass","copy","cpu","credit-card","crop",
	"crosshair","crown",
	"database","delete","diamond","disc","dollar-sign","download","droplet",
	"pencil","pen-line","square-pen","external-link","eye","eye-off",
	"fast-forward","feather","file","file-minus","file-plus","file-text","film","filter","flag","flame","flask-conical",
	"folder","folder-plus","frown",
	"gamepad-2","gauge","gem","ghost","gift","git-branch","github","glass-water","globe","grab","grid-2x2","group",,
	"hammer","hard-drive","hash","headphones","heart","hexagon","highlighter","history","home","hourglass",
	"image","inbox","infinity","info","italic",
	"key","keyboard",
	"lamp","laptop","layers","layout","layout-grid","library","life-buoy","lightbulb","link","link-2","list","loader",
	"lock","log-in","log-out",
	"magnet","mail","map","map-pin","maximize","maximize-2","medal","megaphone","menu","message-circle","message-square",
	"mic","mic-off","minimize","minimize-2","minus","minus-circle","monitor","moon","more-horizontal","more-vertical",
	"mouse","move","music",
	"navigation","network",
	"octagon","package","paintbrush","palette","pause","pen-tool","percent","phone","pie-chart","pin","play","plug",
	"plug-zap","plus","plus-circle","pocket","power","printer","puzzle",
	"quote",
	"radio","refresh-ccw","refresh-cw","repeat","rewind","rocket","rotate-ccw","rotate-cw","rss","ruler",
	"save","scissors","screen-share","search","send","server","settings","settings-2","share","share-2","shield",
	"shield-off","shield-check","shopping-bag","shopping-cart","shuffle","sidebar","signal","panel-left","skip-back","skip-forward",,
	"skull","sliders","sliders-horizontal","smartphone","smile","snowflake","sparkles","speaker","sprout","square",
	"star","stop-circle","sun","sunrise","sunset","swords",
	"table","tablet","tag","target","terminal","thermometer","thumbs-down","thumbs-up","timer","toggle-left",
	"toggle-right","tool","tornado","trash","trash-2","trending-down","trending-up","triangle","trophy","truck","tv",
	"type",
	"umbrella","underline","undo","unlink","unlock","upload","user","user-check","user-minus","user-plus","user-x","users",
	"video","video-off","voicemail","volume","volume-1","volume-2","volume-x",
	"wand-2","watch","waves","webcam","wifi","wifi-off","wind","wrench",
	"x","x-circle","x-octagon","x-square",
	"zap","zap-off","zoom-in","zoom-out"
)

$lines = New-Object System.Collections.Generic.List[string]
$missing = New-Object System.Collections.Generic.List[string]
foreach ($name in $Wanted) {
    $pat = "(?:\[\s*'$name'\s*\]|[^A-Za-z0-9_]$name)\s*=\s*\{\s*(\d{6,})\s*,\s*\{\s*48\s*,\s*48\s*\}\s*,\s*\{\s*(\d+)\s*,\s*(\d+)\s*\}\s*\}"
    $m = [regex]::Match($raw, $pat)
    if ($m.Success) {
        $id = $m.Groups[1].Value; $ox = $m.Groups[2].Value; $oy = $m.Groups[3].Value
        $lines.Add("`t[`"$name`"] = { $id, 48, 48, $ox, $oy },")
    } else {
        $missing.Add($name)
    }
}

$header = @"
-- AUTO-GENERATED by tools/ExtractIcons.ps1 -- do not edit by hand.
-- Icon data: latte-soft/lucide-roblox 0.1.3 (MIT License) https://github.com/latte-soft/lucide-roblox
-- Icons: Lucide 0.363.0 (ISC License) https://lucide.dev
-- Format per entry: ["name"] = { AssetId, RectWidth, RectHeight, OffsetX, OffsetY }
return {
"@

$out = $header + "`n" + ($lines -join "`n") + "`n}`n"
$dest = Join-Path $PSScriptRoot "..\src\Core\IconMap.lua"
[System.IO.File]::WriteAllText($dest, $out)

Write-Host ("Wrote {0} icons -> {1}" -f $lines.Count, (Resolve-Path $dest))
if ($missing.Count -gt 0) { Write-Host ("MISSING ({0}): {1}" -f $missing.Count, ($missing -join ", ")) }
